# Generated by Django 4.1.3 on 2023-05-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0003_review_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='label',
            field=models.CharField(choices=[('Option 1', 'positive'), ('Option 2', 'negative'), ('Option 3', 'mixed')], max_length=20),
        ),
    ]
