# Generated by Django 4.1.3 on 2023-05-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0004_alter_review_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='hospitel',
            new_name='hospital',
        ),
        migrations.AlterField(
            model_name='review',
            name='label',
            field=models.CharField(max_length=20),
        ),
    ]
